app:
  name: 'CurrencyExchangeApp'
  port: '3080'

database:
  dsn: 'root:123@tcp(mysql:3306)/exchangeApp?charset=utf8mb4&parseTime=True&loc=Local'
  MaxIdleCONNS: 10
  MaxOpenCONNS: 100

redis:
  addr: 'redis:6379'
  password: ''
  db: 0

